spring.application.name=bloodlink-api

# Database connection (Neon PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-polished-term-b31ptxh6-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_eoCGcXDQ1Ik0
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Connection pool (Neon recommends this for serverless Postgres)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

jwt.secret=this-is-a-temporary-dev-secret-change-this-later-to-something-long-and-random
jwt.expiration=86400000

gemini.api.key=AIzaSyAl4Y4w8Rc8IhB1pmCoP5MifKbcT_avPcM
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent